### ISSUE TITLE
Coverage is only partial.

### ISSUE THREAD

**Issue by MrJoy** [parro-it/canibekikked#3]
While Kik's motivation for acting was the perceived need to protect their trademark (they were [misguided](https://www.eff.org/deeplinks/2013/11/trademark-law-does-not-require-companies-tirelessly-censor-internet) here, but believed they had to), checking for trademarks alone will not protect any package author.

Basically, the [NPM dispute resolution policy](https://www.npmjs.com/policies/disputes) shows that they are willing to transfer ownership arbitrarily if they think it is prudent to do so.  Note that:
1. Example #3 does not state that Foo Inc has a trademark on the term `foo` -- and in fact trademarks aren't mentioned **at all**.
2. According to their own Medium post, Kik never actually provided any proof of having a trademark to NPM
3. There's no specificity around jurisdiction in that document (although [others](https://www.npmjs.com/policies/dmca) imply that California law may be the frame of reference they operate under)
4. [Their own trademark policy](https://www.npmjs.com/policies/trademark#nominative-use---no-need-to-type--on-twitter) suggests they've been well-advised on US trademark law, and would have known that Kik was being overzealous, but they chose to remove Azer's ownership of the name anyway -- which strongly supports the idea that they are willing to reassign ownership of a name even in absence of a compelling legal reason

**Comment by parro-it** [comment]
This tool is not meant to protect us for any possible incident... 

It just check if you own any repo with a name trademarked in US.

**Comment by MrJoy** [comment]
The name of the tool is confusing then, as trademarks were only tangentially relevant to the Kik issue.
