### ISSUE TITLE
Name is misleading.

### ISSUE THREAD

**Issue by MrJoy** [parro-it/canibekikked#5]
As this tool only checks for trademark overlap, the name is highly misleading.

The Kik issue is irrelevant to trademark law, even though Kik was motivated by the protection of their trademark:  Had Kik not had a registered trademark, they still could have asked NPM for the package and NPM still likely would have granted it under their T&Cs.

**Comment by ghost** [comment]
Pretty much, can't we have a more descriptive name for this?

**Comment by parro-it** [comment]
Thank you for the suggestion. But I like the name. 
I think description of repository and module explains what is tool is for:

> Tool to check if any of your NPM repositories name is trademarked

It does not try to do more than this. It's not a tool to solve others problems that NPM repository has.

**Comment by MrJoy** [comment]
That you _like_ the name does not change the fact that it's a misleading and reactionary response that needlessly vilifies a party who acted in good faith, and according to their perceived legal duties.  (See also:  Lapp Test)

The name of your tool is literally assigning blame to the wrong party, and as such it is at best misleading and at worst defamatory.
